# 订阅 https://nitter.net/i/lists/1552112375448231938/rss 并存到私人仓库 issue 中
name: update-twitter-rss-issue
on:
  schedule:
    - cron: '*/15 * * * *'
  push:
    branches:
      - main
jobs:
  update-twitter-rss-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2
      - name: Prepare
        run: pnpm install
      - name: Update twitter rss issue
        run: node scripts/update-twitter-rss-issue.js
        env:
          MY_GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}

